# User Configuration for Synthetic Data Generation
# Copy this file and modify the paths to match your setup

# Basic paths - MUST be overridden in user config
tools_path: ""
annotations_path: ""
camera_params: ""
output_dir: "output"
hdri_path: ""

# Dataset parameters
num_images: 1000
poses_per_workspace: 5
workspace_size: 3.5

# Rendering settings
render_width: 1920
render_height: 1080
render_samples: 100

# Effects and augmentation
motion_blur_prob: 0.3
occlusion_prob: 0.3

# Output options
visualize_keypoints: true         # Generate visualization images for debugging
enable_statistics: true           # Enable comprehensive dataset statistics tracking
debug: false
seed: 42                          # For reproducible results

# Advanced settings (usually don't need to change)
tool_scale_range: [0.2, 0.35]
tool_rotation_range: [-0.4, 0.4]
tool_z_variation: [-0.05, 0.05]
min_tool_distance: 0.2
max_placement_attempts: 100

# Camera parameters
camera_height_range: [2.0, 3.5]
camera_offset_range: [-0.8, 0.8]
camera_rotation_range: [-0.3, 0.3]
camera_pose_max_attempts: 10
camera_min_distance_threshold: 0.1
camera_max_angle_from_vertical: 60.0
camera_fallback_height: 3.5

# Lighting parameters (adjust for different surgical environments)
main_light_energy_range: [1200, 1800]
fill_light_energy_range: [500, 900]
side_light_energy_range: [300, 600]
ambient_light_range: [0.2, 0.5]

# Light color ranges (RGB 0.0-1.0)
main_light_color:
  r_range: [0.0, 0.5]
  g_range: [0.0, 0.5]
  b_range: [0.0, 0.5]

fill_light_color:
  r_range: [0.0, 0.5]
  g_range: [0.0, 0.5]
  b_range: [0.0, 0.5]

side_light_color:
  r_range: [0.0, 0.5]
  g_range: [0.0, 0.5]
  b_range: [0.0, 0.5]

ambient_light_color:
  r_range: [0.0, 0.5]
  g_range: [0.0, 0.5]
  b_range: [0.0, 0.5]

# Light positioning
main_light_offset_range: [-0.5, 0.5]
main_light_height_range: [2.5, 3.5]
main_light_size_range: [1.0, 1.5]

fill_light_offset_range: [-1.5, 1.5]
fill_light_height_range: [2.0, 3.0]

side_light_offset_range: [-2.0, 2.0]
side_light_height_range: [1.5, 2.5]

# Material parameters
material_ior_range: [1.4, 2.5]
material_roughness_range: [0.1, 0.4]
material_metallic_value: 1.0

# Gold material HSV ranges
gold_hsv_min: [0.03, 0.95, 0.8]
gold_hsv_max: [0.25, 1.0, 1.0]

# Motion blur parameters
motion_blur_length_range: [0.1, 0.5]
motion_offset_range:
  min: [-0.08, -0.08, -0.05]
  max: [0.08, 0.08, 0.05]

# Medical glove occlusion parameters
occlusion_blob_size_range: [0.05, 0.2]
occlusion_blob_count_range: [1, 1]

occlusion_glove_colors:
  - [0.0, 0.2, 0.8]      # Nitrile blue
  - [0.4, 0.0, 0.7]      # Purple nitrile
  - [0.9, 0.9, 0.85]     # Latex white/cream
  - [0.0, 0.6, 0.9]      # Light blue
  - [0.8, 0.85, 0.9]     # Very light blue/white

glove_roughness_range: [0.1, 0.3]

# Occlusion keypoints for different tool types
occlusion_keypoints:
  needle_holder: ['base_left_forcep', 'base_right_forcep']
  tweezers: ['base']

# Keypoint annotation parameters
keypoint_visible_value: 2
keypoint_not_visible_value: 0
keypoint_not_available_value: 0
